# Configuration settings

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SHIP_SPEED = 20
INITIAL_ALIEN_SPEED = 10  # Adjusted for visible movement
INITIAL_PROJECTILE_SPEED = 6
PROJECTILE_SPEED = INITIAL_PROJECTILE_SPEED
BARRIER_POSITION = [(0, -200), (-200, -200), (200, -200)]
ALIEN_ROWS = 3
ALIEN_COLUMNS = 8
ALIEN_MOVE_INTERVAL = 1  # seconds
SHOOT_DELAY = 0.5  # 0.5 second delay between shots
